# Generated by Django 3.0.8 on 2020-07-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200707_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='playeridnumber',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
