# Generated by Django 3.0.8 on 2020-07-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_history_playeridnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
